# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tourist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('CatImg', models.FileField(default='CatImg/None/default.svg', upload_to='CatImg/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('About', models.TextField()),
                ('Stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotel_images', to='tourist.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Itinerarys',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cities', models.CharField(default='cities', max_length=120)),
                ('Day', models.PositiveIntegerField()),
                ('Title', models.CharField(default='title', max_length=120)),
                ('About', models.TextField(default='About')),
                ('Labels', models.TextField(blank=True, null=True)),
                ('Image_One', models.ImageField(blank=True, null=True, upload_to=tourist.models.itenery_img_location)),
                ('Image_Two', models.ImageField(blank=True, null=True, upload_to=tourist.models.itenery_img_location)),
                ('Image_Three', models.ImageField(blank=True, null=True, upload_to=tourist.models.itenery_img_location)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItineraryDays_days', to='tourist.Itinerary')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'ItineraryDays',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageName', models.CharField(max_length=120, unique=True)),
                ('Overview', models.TextField(default=0)),
                ('Destination', models.CharField(max_length=120)),
                ('Flight', models.BooleanField(default=True)),
                ('Hotel', models.BooleanField(default=True)),
                ('Siteseeing', models.BooleanField(default=True)),
                ('Meals', models.BooleanField(default=True)),
                ('PackageDay', models.PositiveSmallIntegerField(default=0)),
                ('PackageNights', models.PositiveSmallIntegerField(default=0)),
                ('Inclusions', models.TextField(default=0)),
                ('Exclusion', models.TextField(default=0)),
                ('ActualPricePerPerson', models.PositiveIntegerField(default=0)),
                ('OfferedPricePerPerson', models.PositiveIntegerField(default=0)),
                ('DepartureCity', models.CharField(max_length=120)),
                ('Image', models.ImageField(default='Package/None/default.png', upload_to=tourist.models.upload_location)),
                ('NightOneLessThanDay', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourist.Category')),
            ],
            options={
                'ordering': ('timestamp',),
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourist.Package'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='package',
            field=models.ManyToManyField(to='tourist.Package'),
        ),
    ]
