# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=30)),
                ('ActImg', models.ImageField(default='ActivitieImg/None/default.png', height_field='heightField', upload_to='ActivitieImg/', width_field='widthField')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=30)),
                ('InclImg', models.ImageField(default='InclusionImg/None/default.png', height_field='heightField', upload_to='InclusionImg/', width_field='widthField')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
                'verbose_name_plural': 'Inclusions',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourist.Activity'),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourist.Inclusion'),
        ),
    ]
