# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_auto_20181019_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tourist.Activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tourist.Category'),
        ),
    ]
