# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0005_auto_20181019_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='package',
            name='inclusion',
        ),
    ]
