# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0006_auto_20181019_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='activity',
            field=models.ManyToManyField(default=2, to='tourist.Activity'),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusion',
            field=models.ManyToManyField(default=1, to='tourist.Inclusion'),
        ),
    ]
