# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0007_auto_20181019_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ActImg',
            field=models.ImageField(default='ActivitieImg/None/default.png', upload_to='ActivitieImg/'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='InclImg',
            field=models.ImageField(default='InclusionImg/None/default.png', upload_to='InclusionImg/'),
        ),
    ]
