# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0008_auto_20181019_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('india', 'India'), ('international', 'International')], max_length=120)),
            ],
        ),
    ]
