# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0012_auto_20181019_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Best_time_for_travel',
            new_name='Best_time_for_travel_from',
        ),
        migrations.AddField(
            model_name='destination',
            name='Best_time_for_travel_to',
            field=models.CharField(choices=[('january', 'JAN'), ('march', 'MAR'), ('april', 'APR')], default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='Highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
