# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0013_auto_20181022_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='package',
        ),
    ]
