# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0016_remove_itinerary_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Itinerary',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourist.Itinerary'),
        ),
    ]
