# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0017_package_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='name of Itenery', max_length=120),
        ),
    ]
