# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0018_itinerary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='caption',
            field=models.CharField(default='name of Itenery', max_length=120),
        ),
    ]
