# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0019_hotelimage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsForPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='1-2', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='caption', max_length=120),
        ),
        migrations.AddField(
            model_name='hotelsforpackage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_name', to='tourist.Hotel'),
        ),
    ]
