# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0020_auto_20181022_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotelsforpackage',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_package', to='tourist.Package'),
        ),
    ]
