# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0022_auto_20181022_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Exclusion',
            new_name='Exclusion_text',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Inclusions',
            new_name='Inclusion_text',
        ),
        migrations.AlterField(
            model_name='package',
            name='Overview',
            field=models.TextField(default='overview of package'),
        ),
    ]
