# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0025_auto_20181024_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydays',
            name='Inclusion',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='Name of itinerary', max_length=120),
        ),
    ]
