# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0026_auto_20181024_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarydays',
            name='Inclusion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Inclusion', to='tourist.Inclusion'),
        ),
    ]
