# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0028_auto_20181024_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydays',
            name='Inclusion',
            field=models.ManyToManyField(to='tourist.Inclusion'),
        ),
    ]
