# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0029_auto_20181024_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.Destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourist.Itinerary'),
        ),
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.ManyToManyField(to='tourist.Activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.Category'),
        ),
        migrations.AlterField(
            model_name='package',
            name='inclusion',
            field=models.ManyToManyField(to='tourist.Inclusion'),
        ),
    ]
