# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0030_auto_20181024_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Flight',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Meals',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Siteseeing',
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='package',
            name='ActualPricePerPerson',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='Exclusion_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='Inclusion_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='OfferedPricePerPerson',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='PackageDays',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='PackageNights',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='cities',
            field=models.CharField(max_length=120),
        ),
    ]
