# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0031_auto_20181024_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='Best_time_for_travel_from',
            field=models.CharField(choices=[('january', 'JAN'), ('march', 'MAR'), ('april', 'APR')], max_length=120),
        ),
        migrations.AlterField(
            model_name='destination',
            name='Best_time_for_travel_to',
            field=models.CharField(choices=[('january', 'JAN'), ('march', 'MAR'), ('april', 'APR')], max_length=120),
        ),
    ]
