# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0033_auto_20181024_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tourist.Itinerary'),
        ),
    ]
