# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0034_auto_20181024_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='NightOneLessThanDay',
        ),
    ]
