# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0035_remove_package_nightonelessthanday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
