# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0038_auto_20181029_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteltest',
            name='facilitiy',
            field=models.CharField(max_length=120),
        ),
    ]
