# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0039_auto_20181030_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteltest',
            old_name='facilitiy',
            new_name='facility',
        ),
    ]
