# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0040_auto_20181030_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteltest',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
