# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0041_hoteltest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteltest',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='hoteltest',
            name='hotel',
        ),
    ]
