# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0042_auto_20181031_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteltest',
            name='facility',
            field=models.CharField(default='facility', max_length=120),
        ),
    ]
