# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0044_remove_hoteltest_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='cities',
        ),
    ]
