# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0047_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='images',
            field=models.URLField(default='/images'),
        ),
    ]
