# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0049_auto_20181105_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='images',
            field=models.URLField(blank=True, default='/images', null=True),
        ),
    ]
