# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0050_auto_20181105_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='images',
            field=models.URLField(default='/image'),
        ),
    ]
