# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0051_auto_20181105_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
