# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0054_auto_20181105_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydays',
            name='Inclusion',
        ),
    ]
