# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0057_auto_20181105_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='Destination_type',
            new_name='DestinationType',
        ),
    ]
