# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0058_auto_20181117_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
