# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0059_category_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='test',
            field=models.CharField(max_length=120),
        ),
    ]
