# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0060_auto_20181117_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
