# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0064_auto_20181119_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='1-2', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_for_name', to='tourist.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='hotelStars',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel',
            field=models.ManyToManyField(to='tourist.IncludedHotel'),
        ),
    ]
