# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0065_auto_20181119_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedhotel',
            name='day',
            field=models.CharField(default='1-2', max_length=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='hotelStars',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
